root_dir: /home/ud202080021/ToBaFu/BUS_file
dataset: BUS250
topo_feature: BUS250_F


data:
  data_dir: ${root_dir}/data/${dataset}
  feature_info: ${root_dir}/data/topo_features/${topo_feature}.csv
  train_size: 0.8
  zero_count_threshold: 125
  batch_size:
    topo_train: 256
    img_train: 256
    test: 64
 
train:
  topo_feature: ${topo_feature}
  ckpt_dir: ${root_dir}/experiment/
  topo:
    weight_decay: 1e-4
    num_epochs: 100
    patience: 20
    learning_rate: 1e-4
    lr_patience: 10
    lr_decay: 0.5
    dropout_rate: 0.5
    num_blocks: 6
    hidden_size: 512

  img:
    weight_decay: 0.05
    num_epochs: 100
    patience: 20
    learning_rate: 1e-4
    lr_patience: 10
    lr_decay: 0.5
    dropout_rate: 0.5

test:
  model_path: ${root_dir}/experiment/BUS250_F_03-25-12-07-39/
  num_classes: ${train.num_classes}
  topo_model:
    input_size: ${train.topo.input_size}
    num_blocks: ${train.topo.num_blocks}
    hidden_size: ${train.topo.hidden_size}



